import { Roboto_Mono} from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const robotoMono = Roboto_Mono({ subsets: ["latin"] , 
                                 weight:["100" , "200" , "300" , "400" , "500" ,"600" , "700"],
                                 variable: '---font-robotoMono' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoMono.variable}>
        <Header />
        {children}</body>
    </html>
  );
}
